language: java
sudo: false
services:
  - docker
jdk:
  - openjdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - addgroup --gid 150 intershop && adduser -u 150 -G intershop -D intershop -s /bin/sh
install:
  - su - ./gradlew assemble
before_script:
  - su - echo -e "gradle.publish.key=$APIKEY\ngradle.publish.secret=$APISECRET" > $HOME/.gradle/gradle.properties
  - su - cd testdocker && ./createimage.sh && cd ..
script:
  - su - ./buildTravis.sh
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/19d1516a0a3505ee7489
    on_success: change
    on_failure: always
    on_start: never