language: java
sudo: true
services:
  - docker
jdk:
  - openjdk8
before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
before_install:
  - sudo addgroup --gid 150 intershop
  - sudo adduser --uid 150 --ingroup intershop --shell /bin/sh intershop
install:
  - sudo su - intershop -c ./gradlew assemble
before_script:
  - sudo su - intershop -c echo -e "gradle.publish.key=$APIKEY\ngradle.publish.secret=$APISECRET" > $HOME/.gradle/gradle.properties
  - sudo su - intershop -c d testdocker && ./createimage.sh && cd ..
script:
  - sudo su - intershop -c ./buildTravis.sh
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/19d1516a0a3505ee7489
    on_success: change
    on_failure: always
    on_start: never