# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run build and tests

on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    environment: CIRelease
    runs-on: ubuntu-latest

    steps:
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --all --tags
      - name: Run docker login
        run: echo ${{ secrets.DOCKERPASSWD }} | docker login -u ${{ secrets.DOCKERUSER }} --password-stdin
      - name: Run ish docker login
        run: echo ${{ secrets.ISDOCKERPASSWD }} | docker login -u ${{ secrets.ISDOCKERUSER }} --password-stdin docker.intershop.de
      - name: Create Test container
        run: cd testdocker && ./createimage.sh && cd ..
      - name: Run gradle assemble
        run: ./gradlew assemble
      - name: Build and test with Gradle
        env:
          JAVA_OPTS: "-Xmx1024M -XX:MaxPermSize=512M -XX:ReservedCodeCacheSize=512M"
          GRADLE_OPTS: "-Dorg.gradle.daemon=true"
        run: ./gradlew test build -s --scan
      - name: Post Build
        run: rm -f $HOME/.gradle/gradle.properties && rm -f $HOME/.docker/config.json
