# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Run build and tests

on:
  push:
    branches:
      - '**'
  pull_request:
    branches: [ master ]

jobs:
  build:
    permissions:
      checks: write
      pull-requests: write
      contents: read
    environment: CIRelease
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: IntershopCommunicationsAG/.github/actions/gradle-plugin-setup@v1.0
      - name: Prepare Docker
        uses: ./.github/actions/prepare-docker
        with:
          docker-user: ${{ secrets.DOCKERUSER }}
          docker-password: ${{ secrets.DOCKERPASSWD }}
      - name: Build
        uses: IntershopCommunicationsAG/.github/actions/gradle-plugin-build@v1.0
